// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhcyfqjcklghqyvqmczd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoY3lmcWpja2xnaHF5dnFtY3pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NjgyNTksImV4cCI6MjA2NzU0NDI1OX0.1QUR8BTuVjU5lklJVUvMxEEh7Yd1RzgrP7hJ1jUC_K0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});